import { StyleSheet } from 'react-native';
import { Typography } from '../../constants/Typography';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F9FAFB',
  },
  content: {
    flex: 1,
  },
  contentContainer: {
    paddingBottom: 100,
  },
  section: {
    backgroundColor: '#FFFFFF',
    marginTop: 12,
    padding: 16,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  sectionTitle: {
    ...Typography.h3,
    fontSize: 16,
    color: '#111827',
  },
  viewAllButton: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  viewAllText: {
    ...Typography.body,
    fontSize: 14,
    color: '#2563EB',
    marginRight: 4,
  },
  auditScoreSection: {
    alignItems: 'center',
    paddingVertical: 20,
  },
  circularProgressContainer: {
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  circularProgressText: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  scoreNumber: {
    ...Typography.h1,
    fontSize: 32,
    color: '#2563EB',
  },
  auditTitle: {
    ...Typography.h3,
    fontSize: 16,
    color: '#111827',
    marginTop: 12,
  },
  auditSubtitle: {
    ...Typography.body,
    fontSize: 14,
    color: '#6B7280',
    marginTop: 4,
  },
  rerunButton: {
    marginTop: 16,
    paddingHorizontal: 24,
    paddingVertical: 10,
    backgroundColor: '#2563EB',
    borderRadius: 8,
  },
  rerunButtonText: {
    ...Typography.button,
    fontSize: 14,
    color: '#FFFFFF',
  },
  activityGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  activityCard: {
    width: '48%',
    backgroundColor: '#F9FAFB',
    padding: 12,
    borderRadius: 8,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  activityHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  activityIconContainer: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#E0E7FF',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  activityLabel: {
    ...Typography.body,
    fontSize: 12,
    color: '#6B7280',
    flex: 1,
  },
  activityValue: {
    ...Typography.h3,
    fontSize: 20,
    color: '#111827',
    marginBottom: 4,
  },
  activityChange: {
    ...Typography.body,
    fontSize: 12,
  },
  positiveChange: {
    color: '#10B981',
  },
  negativeChange: {
    color: '#EF4444',
  },
  reviewSummary: {
    marginBottom: 16,
  },
  reviewHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  averageRating: {
    alignItems: 'center',
  },
  ratingNumber: {
    ...Typography.h1,
    fontSize: 36,
    color: '#111827',
  },
  starsRow: {
    flexDirection: 'row',
    marginVertical: 4,
  },
  totalReviews: {
    ...Typography.body,
    fontSize: 12,
    color: '#6B7280',
  },
  ratingBars: {
    flex: 1,
    marginLeft: 20,
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  starLabel: {
    ...Typography.body,
    fontSize: 12,
    color: '#6B7280',
    width: 30,
  },
  barContainer: {
    flex: 1,
    height: 8,
    backgroundColor: '#E5E7EB',
    borderRadius: 4,
    marginHorizontal: 8,
    overflow: 'hidden',
  },
  barFill: {
    height: '100%',
    backgroundColor: '#F59E0B',
    borderRadius: 4,
  },
  countLabel: {
    ...Typography.body,
    fontSize: 12,
    color: '#6B7280',
    width: 30,
    textAlign: 'right',
  },
  quickActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 12,
  },
  actionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: '#F3F4F6',
    borderRadius: 8,
    marginHorizontal: 4,
  },
  actionButtonText: {
    ...Typography.button,
    fontSize: 12,
    color: '#374151',
    marginLeft: 6,
  },
  rankingCard: {
    backgroundColor: '#EFF6FF',
    padding: 16,
    borderRadius: 8,
    marginBottom: 16,
  },
  rankingHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  rankingTitle: {
    ...Typography.h3,
    fontSize: 14,
    color: '#1E40AF',
  },
  rankingValue: {
    ...Typography.h2,
    fontSize: 24,
    color: '#1E40AF',
  },
  rankingChange: {
    ...Typography.body,
    fontSize: 12,
    color: '#10B981',
    marginTop: 4,
  },
  recommendationCard: {
    backgroundColor: '#FFFFFF',
    padding: 16,
    borderRadius: 8,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  iconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  priorityBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  priorityText: {
    ...Typography.body,
    fontSize: 10,
    fontWeight: '600',
  },
  cardTitle: {
    ...Typography.h3,
    fontSize: 14,
    color: '#111827',
    marginBottom: 4,
  },
  cardDescription: {
    ...Typography.body,
    fontSize: 12,
    color: '#6B7280',
    marginBottom: 12,
    lineHeight: 18,
  },
  cardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  readMoreButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: '#2563EB',
    borderRadius: 6,
  },
  readMoreButtonText: {
    ...Typography.button,
    fontSize: 12,
    color: '#FFFFFF',
  },
  dismissText: {
    ...Typography.body,
    fontSize: 12,
    color: '#6B7280',
  },
  activityList: {
    marginTop: 8,
  },
  activityItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  activityIconContainer: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#EFF6FF',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  activityContent: {
    flex: 1,
  },
  activityTitle: {
    ...Typography.body,
    fontSize: 14,
    color: '#111827',
    marginBottom: 2,
  },
  activityTime: {
    ...Typography.body,
    fontSize: 12,
    color: '#6B7280',
  },
  viewButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: '#F3F4F6',
    borderRadius: 6,
  },
  viewButtonText: {
    ...Typography.button,
    fontSize: 12,
    color: '#374151',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 20,
    width: '85%',
    maxHeight: '70%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  modalTitle: {
    ...Typography.h2,
    fontSize: 18,
    color: '#111827',
    flex: 1,
  },
  closeButton: {
    padding: 4,
  },
  modalBody: {
    marginBottom: 20,
  },
  modalDescription: {
    ...Typography.body,
    fontSize: 14,
    color: '#6B7280',
    lineHeight: 20,
  },
  modalFooter: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  modalButton: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    backgroundColor: '#2563EB',
    borderRadius: 8,
  },
  modalButtonText: {
    ...Typography.button,
    fontSize: 14,
    color: '#FFFFFF',
  },
});
