import { StyleSheet } from 'react-native';
import { Typography } from '../../constants/Typography';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F9FAFB',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  backButton: {
    padding: 8,
  },
  headerTitle: {
    ...Typography.h2,
    fontSize: 18,
    color: '#111827',
    marginLeft: 12,
    flex: 1,
  },
  filterButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: '#F3F4F6',
    borderRadius: 6,
  },
  filterButtonText: {
    ...Typography.body,
    fontSize: 12,
    color: '#374151',
    marginRight: 4,
  },
  content: {
    flex: 1,
  },
  contentContainer: {
    padding: 16,
    paddingBottom: 100,
  },
  reviewCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 16,
    marginBottom: 12,
    borderWidth: 2,
  },
  reviewHeader: {
    flexDirection: 'row',
    marginBottom: 12,
  },
  moviePoster: {
    width: 60,
    height: 60,
    borderRadius: 4,
    marginRight: 12,
  },
  reviewInfo: {
    flex: 1,
  },
  movieTitle: {
    ...Typography.h3,
    fontSize: 14,
    color: '#111827',
    marginBottom: 4,
  },
  movieMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  msid: {
    ...Typography.body,
    fontSize: 12,
    color: '#6B7280',
  },
  classification: {
    ...Typography.body,
    fontSize: 10,
    color: '#6B7280',
    marginLeft: 8,
    paddingHorizontal: 6,
    paddingVertical: 2,
    backgroundColor: '#F3F4F6',
    borderRadius: 4,
  },
  starsRow: {
    flexDirection: 'row',
    marginBottom: 4,
  },
  timeAgo: {
    ...Typography.body,
    fontSize: 12,
    color: '#6B7280',
  },
  reviewText: {
    ...Typography.body,
    fontSize: 14,
    color: '#374151',
    lineHeight: 20,
    marginBottom: 12,
  },
  reviewActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  actionButtonText: {
    ...Typography.body,
    fontSize: 12,
    color: '#2563EB',
    marginLeft: 6,
  },
  replySection: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
  },
  replyLabel: {
    ...Typography.body,
    fontSize: 12,
    color: '#6B7280',
    marginBottom: 6,
  },
  replyText: {
    ...Typography.body,
    fontSize: 14,
    color: '#374151',
    lineHeight: 20,
    backgroundColor: '#F9FAFB',
    padding: 12,
    borderRadius: 6,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  filterModal: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    padding: 16,
    maxHeight: '50%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  modalTitle: {
    ...Typography.h3,
    fontSize: 16,
    color: '#111827',
  },
  filterOption: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  selectedFilterOption: {
    backgroundColor: '#EFF6FF',
  },
  filterOptionText: {
    ...Typography.body,
    fontSize: 14,
    color: '#111827',
  },
  selectedFilterOptionText: {
    color: '#2563EB',
    fontWeight: '600',
  },
  replyModalContent: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    padding: 16,
    maxHeight: '80%',
  },
  replyInput: {
    ...Typography.body,
    fontSize: 14,
    color: '#111827',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 8,
    padding: 12,
    minHeight: 120,
    textAlignVertical: 'top',
    marginBottom: 16,
  },
  replyActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  cancelButton: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    marginRight: 8,
  },
  cancelButtonText: {
    ...Typography.button,
    fontSize: 14,
    color: '#6B7280',
  },
  sendButton: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    backgroundColor: '#2563EB',
    borderRadius: 8,
  },
  sendButtonText: {
    ...Typography.button,
    fontSize: 14,
    color: '#FFFFFF',
  },
});
